platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'

pod 'Lockbox'
#pod 'FontAwesomeKit', '~> 2.1.0'
pod 'payworks', '2.7.1'
pod 'payworks.paybutton', '2.7.1'
#pod 'AFNetworking', '2.5.3'
pod 'HockeySDK'
pod 'Firebase', '>= 2.2.0'
