platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'

pod 'Lockbox'
#pod 'FontAwesomeKit', '~> 2.1.0'
pod 'payworks-dev', '2.15.0-PREVIEW02'
pod 'payworks.paybutton-dev', '2.15.0-PREVIEW02'
#pod 'AFNetworking', '2.5.3'
pod 'HockeySDK'
pod 'Firebase', '2.2.0'
