platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git'

pod 'Paybutton', '1.0.0-BETA'
pod 'CocoaLumberjack', '~> 1.8'
pod 'MPBSignatureViewController'
pod 'AFNetworking'
pod 'HockeySDK'
pod 'Firebase', '>= 2.2.0'
